services:
  integration-service:
    build: .
    image: ghcr.io/langrenn-sprint/integration-service:test
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - EVENTS_HOST_SERVER=event-service
      - EVENTS_HOST_PORT=8080
      - PHOTOS_HOST_SERVER=photo-service
      - PHOTOS_HOST_PORT=8080
      - RACE_HOST_SERVER=race-service
      - RACE_HOST_PORT=8080
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
    volumes:
      - type: bind
        source: integration_service/files
        target: /app/files
      - type: bind
        source: error.log
        target: /app/error.log